name              "gamecoach"
maintainer        "Friedrich Kauder"
maintainer_email  "fkauder@gmail.com"
license           "Apache 2.0"
description       "Installs the Gamecoach application"
version           "0.0.1"


depends			  "gc-base"
depends			  "gc-python"
depends           "python"
depends			  "gc-nginx"
depends           "nginx"
depends			  "gc-supervisor"
depends			  "supervisor"
depends			  "gc-postgresql"
depends           "postgresql"
depends           "database"