name              "gamecoach"
maintainer        "Friedrich Kauder"
maintainer_email  "fkauder@gmail.com"
license           "Apache 2.0"
description       "Installs the Gamecoach application"
version           "0.0.1"

depends           "python"
depends           "nginx"
depends			  "supervisor"
depends           "postgresql"
depends           "database"